name: pygbag_build
on: [workflow_dispatch]

jobs:
  build-pygbag:
    name: Build for Emscripten pygbag runtime
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Pygbag
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytmx
        python -m pip install pygame
        python -m pip install pygbag

    - name: Build Pygame project with Pygbag
      run: |
        python -m pygbag --build $GITHUB_WORKSPACE/main.py

    - name: Upload to GitHub Pages branch (gh-pages)
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/web
        clean: true  # Ensures the gh-pages branch is cleared before deployment
